vscode:
  extensions:
    - akamud.vscode-theme-onedark@2.2.2:ubfMBGpcl1wmgUXJQK99Wg==
    - zhuangtongfa.material-theme@3.8.5:g0hzCQNjVo4tGZHXf+w5Mg==
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==